version: "2"

services:
   jenkins:
    container_name: jenkins
    build: "jenkins/"
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: "postgres:9.5"
    env_file:
      - ".env.development"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    image: "redis:3.0-alpine"
    command: redis-server --requirepass devpassword
    volumes:
      - "redis:/var/lib/redis/data"
    ports:
      - "6379:6379"

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "felinefolia.app:create_app()"
    env_file:
      - ".env.development"
    volumes:
      - ".:/felinefolia"
    ports:
      - "8000:8000"

  celery:
    build: .
    command: celery worker -B -l info -A felinefolia.resources.contact.tasks
    env_file:
      - ".env.development"
    volumes:
      - ".:/felinefolia"

volumes:
  postgres:
  redis:
